/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AlumnoSchema extends BaseModel {
  static $columns = ['apellidoMaterno', 'apellidoPaterno', 'curp', 'email', 'id', 'matricula', 'nombre', 'planEstudiosId', 'telefono'] as const
  $columns = AlumnoSchema.$columns
  @column()
  declare apellidoMaterno: string | null
  @column()
  declare apellidoPaterno: string | null
  @column()
  declare curp: string | null
  @column()
  declare email: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare matricula: string | null
  @column()
  declare nombre: string | null
  @column()
  declare planEstudiosId: number | null
  @column()
  declare telefono: string | null
}

export class CalificacionUnidadSchema extends BaseModel {
  static $columns = ['calificacion', 'id', 'inscripcionMateriaId', 'unidadId'] as const
  $columns = CalificacionUnidadSchema.$columns
  @column()
  declare calificacion: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare inscripcionMateriaId: number | null
  @column()
  declare unidadId: number | null
}

export class CarreraSchema extends BaseModel {
  static $columns = ['id', 'nombre'] as const
  $columns = CarreraSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare nombre: string
}

export class CarreraCoordinadorSchema extends BaseModel {
  static $columns = ['carreraId', 'coordinadorId', 'fechaFin', 'fechaInicio', 'id'] as const
  $columns = CarreraCoordinadorSchema.$columns
  @column()
  declare carreraId: number | null
  @column()
  declare coordinadorId: number | null
  @column.date()
  declare fechaFin: DateTime | null
  @column.date()
  declare fechaInicio: DateTime | null
  @column({ isPrimary: true })
  declare id: number
}

export class CoordinadorSchema extends BaseModel {
  static $columns = ['apellidoMaterno', 'apellidoPaterno', 'correo', 'curp', 'id', 'noCedulaProfesional', 'nombre', 'rfc', 'telefono'] as const
  $columns = CoordinadorSchema.$columns
  @column()
  declare apellidoMaterno: string | null
  @column()
  declare apellidoPaterno: string | null
  @column()
  declare correo: string | null
  @column()
  declare curp: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare noCedulaProfesional: string | null
  @column()
  declare nombre: string | null
  @column()
  declare rfc: string | null
  @column()
  declare telefono: string | null
}

export class EdificioSchema extends BaseModel {
  static $columns = ['id', 'nombre', 'numeroSalones'] as const
  $columns = EdificioSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare nombre: string | null
  @column()
  declare numeroSalones: number | null
}

export class GrupoSchema extends BaseModel {
  static $columns = ['carreraId', 'cuatrimestre', 'id', 'nombre', 'periodoId'] as const
  $columns = GrupoSchema.$columns
  @column()
  declare carreraId: number | null
  @column()
  declare cuatrimestre: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare nombre: string | null
  @column()
  declare periodoId: number | null
}

export class GrupoMateriaSchema extends BaseModel {
  static $columns = ['grupoId', 'id', 'materiaId'] as const
  $columns = GrupoMateriaSchema.$columns
  @column()
  declare grupoId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare materiaId: number | null
}

export class GrupoMateriaProfesorSchema extends BaseModel {
  static $columns = ['grupoMateriaId', 'id', 'profesorId'] as const
  $columns = GrupoMateriaProfesorSchema.$columns
  @column()
  declare grupoMateriaId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare profesorId: number | null
}

export class HistorialMateriaSchema extends BaseModel {
  static $columns = ['alumnoId', 'calificacion', 'estatus', 'id', 'materiaId', 'periodoId', 'tipoOportunidad'] as const
  $columns = HistorialMateriaSchema.$columns
  @column()
  declare alumnoId: number | null
  @column()
  declare calificacion: number | null
  @column()
  declare estatus: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare materiaId: number | null
  @column()
  declare periodoId: number | null
  @column()
  declare tipoOportunidad: string | null
}

export class HorarioSchema extends BaseModel {
  static $columns = ['diaSemana', 'grupoMateriaId', 'horaFin', 'horaInicio', 'id', 'salonId'] as const
  $columns = HorarioSchema.$columns
  @column()
  declare diaSemana: string
  @column()
  declare grupoMateriaId: number | null
  @column()
  declare horaFin: string | null
  @column()
  declare horaInicio: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare salonId: number | null
}

export class InscripcionSchema extends BaseModel {
  static $columns = ['alumnoId', 'cuatrimestreActual', 'estadoAcademico', 'id', 'periodoId'] as const
  $columns = InscripcionSchema.$columns
  @column()
  declare alumnoId: number | null
  @column()
  declare cuatrimestreActual: number | null
  @column()
  declare estadoAcademico: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare periodoId: number | null
}

export class InscripcionMateriaSchema extends BaseModel {
  static $columns = ['grupoMateriaId', 'id', 'inscripcionId'] as const
  $columns = InscripcionMateriaSchema.$columns
  @column()
  declare grupoMateriaId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare inscripcionId: number | null
}

export class MateriaSchema extends BaseModel {
  static $columns = ['id', 'nombre'] as const
  $columns = MateriaSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare nombre: string
}

export class PeriodoSchema extends BaseModel {
  static $columns = ['anio', 'id', 'nombre'] as const
  $columns = PeriodoSchema.$columns
  @column()
  declare anio: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare nombre: string
}

export class PlanEstudioSchema extends BaseModel {
  static $columns = ['carreraId', 'id', 'nombre', 'vigente'] as const
  $columns = PlanEstudioSchema.$columns
  @column()
  declare carreraId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare nombre: string
  @column()
  declare vigente: string
}

export class PlanEstudiosMateriaSchema extends BaseModel {
  static $columns = ['creditos', 'cuatrimestre', 'id', 'materiaId', 'planEstudiosId'] as const
  $columns = PlanEstudiosMateriaSchema.$columns
  @column()
  declare creditos: number | null
  @column()
  declare cuatrimestre: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare materiaId: number | null
  @column()
  declare planEstudiosId: number | null
}

export class ProfesorSchema extends BaseModel {
  static $columns = ['apellidoMaterno', 'apellidoPaterno', 'curp', 'email', 'especialidad', 'id', 'noCedulaProfesional', 'nombre', 'rfc', 'telefono'] as const
  $columns = ProfesorSchema.$columns
  @column()
  declare apellidoMaterno: string | null
  @column()
  declare apellidoPaterno: string | null
  @column()
  declare curp: string | null
  @column()
  declare email: string | null
  @column()
  declare especialidad: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare noCedulaProfesional: string | null
  @column()
  declare nombre: string | null
  @column()
  declare rfc: string | null
  @column()
  declare telefono: string | null
}

export class SalonSchema extends BaseModel {
  static $columns = ['edificioId', 'id', 'nombre'] as const
  $columns = SalonSchema.$columns
  @column()
  declare edificioId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare nombre: string | null
}

export class UnidadSchema extends BaseModel {
  static $columns = ['id', 'nombre', 'numeroUnidad', 'planEstudiosMateriaId'] as const
  $columns = UnidadSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare nombre: string | null
  @column()
  declare numeroUnidad: number | null
  @column()
  declare planEstudiosMateriaId: number | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
